---
- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: install apache
    yum:
        name: apache
        start: installed
  - name: start httpd
    service:
      name: httpd
      service: started